### ISSUE TITLE
Missing type declaration files

### ISSUE THREAD

**Issue by jcs090218** [hugocxl/react-echarts#21]
### Description

```
import { EChart } from '@hcorta/react-echarts';
```

This will give me an error `Could not find a declaration file for module xxx`.

### Link to Reproduction

n/a

### Steps to reproduce

1. Install this package in your project:

```
npm i @hcorta/react-echarts
```

2. Use this package in your `tsx` file.

### JS Framework

React (TS)

### Version

2.0.0

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by hugocxl** [comment]
HI @jcs090218! This package is not published under that organization, see the install instructions in the docs:
https://hugocxl.github.io/react-echarts/docs/installation

Hope that helps!

**Comment by jcs090218** [comment]
Thank you!
