### ISSUE TITLE
How to use registerMap

### ISSUE THREAD

**Issue by OctoD** [hugocxl/react-echarts#23]
### Subject

component

### Description

Reading the docs there's nothing about "registering" a map with geoJSON data.

The same by reading the code.

May I ask you if this is possible and how? Tnx.

**Comment by hugocxl** [comment]
Hi there @OctoD! That functionality isn't related to React, so you can just follow ECharts documentation about it.

**Comment by OctoD** [comment]
Yes I know it, but how can be it used by the component directly?

**Comment by hugocxl** [comment]
```
import { registerMap } from 'echarts'

registerMap( // ....your options )

export function App() {
  // ... your react code
}
```

ECharts has great docs, check here: https://echarts.apache.org/en/api.html#echarts.registerMap

Hope that helps!
