### ISSUE TITLE
Animation still reset each time data is changed

### ISSUE THREAD

**Issue by YuriGor** [hugocxl/react-echarts#25]
Hello, thanks for making this working again! 

I faced same issue which is mentioned below as resolved in v1.0.4

              Fixed in `v1.0.4`, thanks to @brandanking-decently contribution.

_Originally posted by @hugocxl in https://github.com/hugocxl/react-echarts/issues/20#issuecomment-1944502787_
            
So I have this version, still each data change cause my barchart to disappear and raise from zero instead of smoothly sliding bars up and down to new values.

Here is my way of doing things, please help

```js
import { EChart } from '@kbox-labs/react-echarts';
import {
  BarChart,
} from 'echarts/charts';
import {
  GridComponent,
  TooltipComponent,
  TitleComponent,
} from 'echarts/components';
import {
  CanvasRenderer,
} from 'echarts/renderers';

import merge from 'lodash/merge';
import map from 'lodash/map';
import { shadedColors } from './color/colors';

const defaultStyle = { height: '', width: '100%' };
const defaultOptions = {
  grid: [
    {
      left: 0,
      top: 0,
      right: 0,
      bottom: 0,
      containLabel: true,
    },
  ],
  color: map(shadedColors.slice(1), 0),
};

export default function Echarts({
  option = {}, style = {}, ...props
}) {
  const p = merge({}, props, defaultOptions, option);

  return (
    <EChart
      use={[
        BarChart,
        GridComponent,
        TooltipComponent,
        TitleComponent,
        CanvasRenderer,
      ]}
      renderer="canvas"
      lazyUpdate
      notMerge {/* adding/removing notMerge has no effect */}
      theme="theme_name"
      style={{ ...defaultStyle, ...style }}
      {...p}
    />
  );
}
```

**Comment by hugocxl** [comment]
@YuriGor hi! Mind providing a reproducible example, so I can test it out? Thanks!

**Comment by YuriGor** [comment]
Please check older issue #20 
I updated react-recharts to v1.0.4 and animation of that pie chart is still resetting
https://stackblitz.com/edit/vitejs-vite-vsb5cd?file=package.json
Maybe makes better sense to reopen #20 then
