### ISSUE TITLE
Regression: Charts don't dynamically resize

### ISSUE THREAD

**Issue by mattsbennett** [hugocxl/react-echarts#49]
### Description

Charts don't dynamically resize on viewport width changes (though they still layout responsively on initial load). This is a regression from `1.2.1` (perhaps other interim versions).

### Link to Reproduction

https://stackblitz.com/edit/react-xfumjc?file=package.json,src%2FApp.js,src%2FApp.js

### Steps to reproduce

1. Go to https://stackblitz.com/edit/react-xfumjc?file=package.json,src%2FApp.js,src%2FApp.js
2. Observe on resizing the stackblitz preview pane, the chart doesn't dynamically resize with the preview window.
3. Now use the trash can in the dependences pane to remove version 1.3.1
4. Install 1.2.1 by entering @kbox-labs/react-echarts@1.2.1 in the "Enter package name" field, pressing Enter
5. After reloading the preview, the chart dynamically resizes on preview window width change

### Version

1.3.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by hugocxl** [comment]
@mattsbennett I'm working on this, I'll try to publish a fix today

**Comment by hugocxl** [comment]
@mattsbennett fixed issue on `v1.4.0`. Tried out in your example and working as expected.

**Comment by mattsbennett** [comment]
Works great, thanks @hugocxl !
