### ISSUE TITLE
How can I open a PR

### ISSUE THREAD

**Issue by brandanking-decently** [hugocxl/react-echarts#56]
### Subject

Pull Requests

### Description

I have created a small update to separate out some of the logic so it is not all just inside the useEcharts hook. I would like to provide you with a PR but currently I am unable too. Simple changes mainly, but would have minor performance impacts as functions aren't being recreated on every render etc

**Comment by hugocxl** [comment]
Hi @brandanking-decently, can't you open a PR? what's your issue exactly?

**Comment by brandanking-decently** [comment]
Hey @hugocxl when trying to push a new branch to create a PR from I can't. The PR itself isn't one that would specifically fix anything (does fix animations not being set by default) but I've separated out the code more so that the useEcharts hook doesn't have so many functions that could be outside of it. Reducing the times the functions are initialised etc

**Comment by hugocxl** [comment]
mmm... seems not related to the repo itself. Have you forked the project?
